### ISSUE TITLE
launcher.dll could not be found.

### ISSUE THREAD

**Issue by marcikaa78** [PiMoNFeeD/csgo-src#10]
-YES it's in the (correct) bin folder 
-YES I did get a successful compile
-YES I used visual studio 2015

**Comment by PiMoNFeeD** [comment]
"launcher.dll not found" and "could not load launcher dll specified module isn't found" are two different errors, clarify which one you get

**Comment by marcikaa78** [comment]
Failed to load the launcher.dll the specified module could not be found, thats the error.

**Comment by PiMoNFeeD** [comment]
> Failed to load the launcher.dll the specified module could not be found, thats the error.

that means that some dependency in your engine isnt present, check what dlls launcher.dll loads and check their dependencies (for example engine.dll depends on phonon3d.dll)

**Comment by marcikaa78** [comment]
And how to get those dlls? If I kbow their names?

**Comment by marcikaa78** [comment]
Copied some dlls and it works! Yeeeey

**Comment by PiMoNFeeD** [comment]
you aren't meant to use bin folder produced by this codebase as-is, you're supposed to put it in your csgo 2017 folder replacing existing files
