### ISSUE TITLE
Parent cvar in client.dll not allowed

### ISSUE THREAD

**Issue by DiegoArmando-27** [PiMoNFeeD/csgo-src#11]
Sorry if it's a necro repository but after building it gets this errors:

Parent cvar in client.dll not allowed (weapon_max_before_cleanup)
Parent cvar in client.dll not allowed (weapon_auto_cleanup_time)
Parent cvar in client.dll not allowed (snd_max_pitch_shift_inaccuracy)
Parent cvar in client.dll not allowed (steam_controller_haptics)
Parent cvar in client.dll not allowed (mp_endmatch_votenextleveltime)
Parent cvar in client.dll not allowed (mp_verbose_changelevel_spew)
Parent cvar in client.dll not allowed (cl_remove_old_ugc_downloads)
Particles: Missing 'particles/money_fx.pcf'
maxplayers set to 64

**Comment by PiMoNFeeD** [comment]
these are not errors and they dont affect workability
