### ISSUE TITLE
Game instantly crashes 

### ISSUE THREAD

**Issue by DiegoArmando-27** [PiMoNFeeD/csgo-src#12]
As you said in #11, those warnings are not errors
But the game instantly crashes after launch
Yes, I'm using 18.05.17 game files
Yes, the build was succesful
Yes, I used CS:S menu resources 
Using VS2015

**Comment by PiMoNFeeD** [comment]
use your visual studio debugger to figure out where it crashes, I dont know what's going on for you

**Comment by DiegoArmando-27** [comment]
![image](https://github.com/SourceSDK2013Ports/csgo-src/assets/73876067/1c69c0af-7c6a-4d19-bb00-4f4d1621d6a7)
Don't think that's normal

**Comment by PiMoNFeeD** [comment]
look at where it breaks in code

**Comment by DiegoArmando-27** [comment]
![image](https://github.com/SourceSDK2013Ports/csgo-src/assets/73876067/843865bd-af99-40cb-a0d5-90cfc0b2c7ed)
Only show me a disassembly

**Comment by PiMoNFeeD** [comment]
then you dont have the right binaries or pdbs

**Comment by DiegoArmando-27** [comment]
I just did something and now it's at least opens. Now it's another break
![image](https://github.com/SourceSDK2013Ports/csgo-src/assets/73876067/65ba74b1-773a-4423-945e-0c58ef66272a)
And shows me this piece of code (keyvalues.cpp, line 746)
![image](https://github.com/SourceSDK2013Ports/csgo-src/assets/73876067/469307a8-e8b9-4756-9102-c8f1366f074a)

**Comment by DiegoArmando-27** [comment]
> ![image](https://private-user-images.githubusercontent.com/73876067/335945086-1c69c0af-7c6a-4d19-bb00-4f4d1621d6a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTM5NjcsIm5iZiI6MTcxNzQ5MzY2NywicGF0aCI6Ii83Mzg3NjA2Ny8zMzU5NDUwODYtMWM2OWMwYWYtN2M2YS00ZDE5LWJiMDAtNGY0ZDE2MjFkNmE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA5MzQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5YmQ4ZTYxMDI2OGRlOWU2NDRmMTQ3Y2E1YjQzOWJjMzUzNDc2NDA5YzBjMzUyYjQ0NjFkMDY3Y2QwYzU2ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hRat6VKVthtxsgz3nT7X_2gRfot7Tpe0po88xeTOYNs)

Also this exception happens after replacement launcher.dll to built version

**Comment by DiegoArmando-27** [comment]
Giving up
