### ISSUE TITLE
linux?

### ISSUE THREAD

**Issue by nn-firc** [PiMoNFeeD/csgo-src#2]
add linux support

**Comment by PiMoNFeeD** [comment]
I don't have linux and I don't really know how to develop under linux at all, so thats a no for me

**Comment by nn-firc** [comment]
> I don't have linux and I don't really know how to develop under linux at all, so thats a no for me

ok，thanks

**Comment by nn-firc** [comment]
the togl are still here will you del it？

**Comment by PiMoNFeeD** [comment]
> the togl are still here will you del it？

im pretty sure it does nothing under win32

**Comment by nn15** [comment]
> > the togl are still here will you del it？
> 
> 
> 
> im pretty sure it does nothing under win32
it's for linux so you can remove it

**Comment by nn-firc** [comment]
> > the togl are still here will you del it？
> 
> 
> 
> im pretty sure it does nothing under win32

it is for linux's，it means driectx to opengl，so you can remove it
