### ISSUE TITLE
Dependencies to run game

### ISSUE THREAD

**Issue by NOMFPS** [PiMoNFeeD/csgo-src#3]
How files are required i read the cs:s for GUI but
I mean models, maps and textures 
From steam csgo 2022? or where

**Comment by PiMoNFeeD** [comment]
makes total sense to run 2017 code on 2022 build
you know what leaked code is this and the build needed to run it has never changed

**Comment by NOMFPS** [comment]
So what is the purpose of the project?
educational purpose?
Open Source csgo mod?
or what?

**Comment by PiMoNFeeD** [comment]
> So what is the purpose of the project? educational purpose? Open Source csgo mod? or what?

its stated in readme :facepalm:
