### ISSUE TITLE
How to running it?

### ISSUE THREAD

**Issue by ghost** [PiMoNFeeD/csgo-src#6]
How to running it? It shows error: can't find background image or "Could not loading library matchmaking".

**Comment by PiMoNFeeD** [comment]
> How to running it? It shows error: can't find background image or "Could not loading library matchmaking".

are you trying to run it on current build?

**Comment by ghost** [comment]
YES, sir, current build...

**Comment by PiMoNFeeD** [comment]
> YES, sir, current build...

the only csgo leak ever existed which this repo is based on does NOT work on current build

**Comment by ghost** [comment]
So how can I running it?

**Comment by PiMoNFeeD** [comment]
the answer to that is in the root of src folder, the only .txt file
you will also need to use css resources and scripts
