### ISSUE TITLE
sounds_manifest.txt error

### ISSUE THREAD

**Issue by IAhmadGT** [PiMoNFeeD/csgo-src#9]
Unable to load manifest file 'scripts/game_sounds_manifest.txt'

but it exists in the scripts folder!!

**Comment by PiMoNFeeD** [comment]
well clearly it cant find it, if it IS there then check your gameinfo.txt for search paths

**Comment by IAhmadGT** [comment]
I used the gameinfo that you included in the game folder

**Comment by PiMoNFeeD** [comment]
then your game files are corrupted in some way

**Comment by IAhmadGT** [comment]
it got fixed by removing write_game in "game+write_game		csgo"  but the game now is instant crashing

**Comment by PiMoNFeeD** [comment]
I dont know what's wrong with your game installation but clearly its not ok
also the change you made does not even affect file searching and you should not keep it

**Comment by IAhmadGT** [comment]
I use the 2017 depots I added the your compiled client.dll and server.dll, what should I do!!

**Comment by PiMoNFeeD** [comment]
compile the entire engine maybe? obviously JUST these two dlls will never work, they barely have anything to do with most of the changes to the codebase

**Comment by IAhmadGT** [comment]
okay I did that that after I commented and well it still crashing
also hammer doesn't work :)

**Comment by PiMoNFeeD** [comment]
I never touched anything tools-related

**Comment by IAhmadGT** [comment]
anyways thank you, I give up :')
